[package]
name = "speakers_nifaudio"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "speakers_nifaudio"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.30.0"
lazy_static = "1.0"
rodio = "0.9.0"
